/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.bancodehoras;

import javax.swing.JDesktopPane;

/**
 *
 * @author juliocesarlealdefaria
 */
public class JInternalFrameDashboard extends javax.swing.JInternalFrame {

    JDesktopPane desktopPane = new JDesktopPane();
    /**
     * Creates new form JInternalFrameDashboard
     */
    public JInternalFrameDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        lblGrafico = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtBuscarColaborador = new javax.swing.JTextField();
        btnBuscarColaborador = new javax.swing.JButton();
        btnAdicionarColaborador = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblListaColaboradores = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        lblColaborador = new javax.swing.JLabel();
        CbbListaColaboradores = new javax.swing.JComboBox<>();
        lblHorasExtras = new javax.swing.JLabel();
        lblNumeroHorasExtras = new javax.swing.JLabel();
        lblHorasPagas = new javax.swing.JLabel();
        lblNumeroHorasPagas = new javax.swing.JLabel();
        lblSaldoAtual = new javax.swing.JLabel();
        lblNumeroSaldoAtual = new javax.swing.JLabel();
        btnAdicionarHoras = new javax.swing.JButton();
        btnRemoverHoras = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblLogout = new javax.swing.JLabel();
        lblPerfil = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(240, 240, 240));
        setPreferredSize(new java.awt.Dimension(767, 494));

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setFont(new java.awt.Font("Fira Sans Semi-Light", 0, 18)); // NOI18N

        jPanel2.setFont(new java.awt.Font("Fira Sans Semi-Light", 0, 13)); // NOI18N

        lblGrafico.setFont(new java.awt.Font("Fira Sans Semi-Light", 0, 36)); // NOI18N
        lblGrafico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGrafico.setText("Gráfico");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(lblGrafico, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(lblGrafico, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Dashboard", jPanel2);

        txtBuscarColaborador.setText("Digite o nome do Colaborador");
        txtBuscarColaborador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarColaboradorActionPerformed(evt);
            }
        });

        btnBuscarColaborador.setText("Buscar");

        btnAdicionarColaborador.setText("Adicionar Colaborador");

        tblListaColaboradores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Colaborador da Silva Neto", "Editar", "Deletar", "120.5"},
                {"Colaboradora de Souza Camões", "Editar", "Deletar", "80"},
                {"Colaborador", "Editar", "Deletar", "20"},
                {"Colaboradora de Souza Camões", "Editar", "Deletar", "55.4"},
                {"Colaborador", "Editar", "Deletar", "10"},
                {"Colaboradora de Souza Camões", "Editar", "Deletar", "-8"},
                {"Colaborador", "Editar", "Deletar", "5"},
                {"Colaboradora de Souza Camões", "Editar", "Deletar", "52"},
                {"Colaborador", "Editar", "Deletar", "12"},
                {"Colaboradora de Souza Camões", "Editar", "Deletar", "8"}
            },
            new String [] {
                "Nome", "Editar", "Deletar", "Saldo"
            }
        ));
        tblListaColaboradores.setShowGrid(false);
        tblListaColaboradores.setShowHorizontalLines(true);
        jScrollPane2.setViewportView(tblListaColaboradores);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtBuscarColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscarColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                        .addComponent(btnAdicionarColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtBuscarColaborador)
                    .addComponent(btnAdicionarColaborador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBuscarColaborador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Colaboradores", jPanel3);

        lblColaborador.setText("Colaborador:");

        CbbListaColaboradores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "João da Silva Gonçalves", "Maria das Dores Dias Alves", "Erllo Melancia de Colher Nowacki", "Jorge Amado dos Santos" }));

        lblHorasExtras.setFont(new java.awt.Font("Fira Sans Semi-Light", 0, 18)); // NOI18N
        lblHorasExtras.setText("Horas extras até a data atual:");

        lblNumeroHorasExtras.setFont(new java.awt.Font("Fira Sans Semi-Light", 0, 18)); // NOI18N
        lblNumeroHorasExtras.setText("120");

        lblHorasPagas.setFont(new java.awt.Font("Fira Sans Semi-Light", 0, 18)); // NOI18N
        lblHorasPagas.setText("Horas pagas:");

        lblNumeroHorasPagas.setFont(new java.awt.Font("Fira Sans Semi-Light", 0, 18)); // NOI18N
        lblNumeroHorasPagas.setText("85");

        lblSaldoAtual.setFont(new java.awt.Font("Fira Sans Semi-Light", 0, 18)); // NOI18N
        lblSaldoAtual.setText("Saldo atual:");

        lblNumeroSaldoAtual.setFont(new java.awt.Font("Fira Sans Semi-Light", 0, 18)); // NOI18N
        lblNumeroSaldoAtual.setText("35");

        btnAdicionarHoras.setText("Adicionar horas");
        btnAdicionarHoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarHorasActionPerformed(evt);
            }
        });

        btnRemoverHoras.setText("Remover horas");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CbbListaColaboradores, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(lblHorasPagas)
                                .addGap(18, 18, 18)
                                .addComponent(lblNumeroHorasPagas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblSaldoAtual))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(lblHorasExtras)
                                .addGap(18, 18, 18)
                                .addComponent(lblNumeroHorasExtras)))
                        .addGap(18, 18, 18)
                        .addComponent(lblNumeroSaldoAtual))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(btnAdicionarHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(btnRemoverHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CbbListaColaboradores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionarHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemoverHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHorasExtras)
                    .addComponent(lblNumeroHorasExtras))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHorasPagas)
                    .addComponent(lblNumeroHorasPagas)
                    .addComponent(lblSaldoAtual)
                    .addComponent(lblNumeroSaldoAtual))
                .addContainerGap(96, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Controle de horas", jPanel4);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblLogout.setText("<html><u>Logout</u>");
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoutMouseClicked(evt);
            }
        });

        lblPerfil.setText("Logo Perfil");

        lblLogo.setFont(new java.awt.Font("Fira Sans Semi-Light", 0, 30)); // NOI18N
        lblLogo.setText("Logo");

        lblTitulo.setFont(new java.awt.Font("Fira Sans Semi-Light", 0, 48)); // NOI18N
        lblTitulo.setText("Banco de horas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblLogo)
                .addGap(45, 45, 45)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblPerfil)
                .addGap(26, 26, 26)
                .addComponent(lblLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPerfil)
                    .addComponent(lblLogo)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Dashboard");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarColaboradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarColaboradorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarColaboradorActionPerformed

    private void lblLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseClicked
        TelaInicial inicio = new TelaInicial();
        inicio.setVisible(true);

        desktopPane.add(inicio);
        this.setContentPane(desktopPane);// TODO add your handling code here:
    }//GEN-LAST:event_lblLogoutMouseClicked

    private void btnAdicionarHorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarHorasActionPerformed

    }//GEN-LAST:event_btnAdicionarHorasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbbListaColaboradores;
    private javax.swing.JButton btnAdicionarColaborador;
    private javax.swing.JButton btnAdicionarHoras;
    private javax.swing.JButton btnBuscarColaborador;
    private javax.swing.JButton btnRemoverHoras;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblColaborador;
    private javax.swing.JLabel lblGrafico;
    private javax.swing.JLabel lblHorasExtras;
    private javax.swing.JLabel lblHorasPagas;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblNumeroHorasExtras;
    private javax.swing.JLabel lblNumeroHorasPagas;
    private javax.swing.JLabel lblNumeroSaldoAtual;
    private javax.swing.JLabel lblPerfil;
    private javax.swing.JLabel lblSaldoAtual;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblListaColaboradores;
    private javax.swing.JTextField txtBuscarColaborador;
    // End of variables declaration//GEN-END:variables
}
